### PR TITLE
Fody experiment: Replace all ConfigureAwait(false) with an assembly level directive

### PR DESCRIPTION
**Pull request by Drise13**
Since we've been inconsistent in applying ConfigureAwait even just within this small code base, this experiment drives an assembly level ConfigureAwait as a set it once and forget about it.

Fody is a compile time injector, manipulating the compile time code to do whatever _weavers_ you have installed and configured. I installed the _ConfigureAwait weaver_ which can apply the ConfigureAwait setting at assembly, class, or method scope. For now, I picked assembly, since we wanted every await call to use the `false` setting. If there is a case where we need to override this, Fody's ConfigureAwait weaver will ignore any explicitly defined setting.

This is an experimental feature add, meaning that this is an optional, new approach compared to how we've configured projects in the past. I think this adds a lot of value since we don't need to waste time on PRs inspecting every await usage, especially that we've missed several places. This should greatly reduce the developer burden here going forward.

### CODE REVIEW

**Comment by erikgabbard** [comment]
Can this be overridden by calling `ConfigureAwait(true)` in cases where you **do** care what thread execution is returned to?

**Comment by Drise13** [comment]
> Can this be overridden by calling `ConfigureAwait(true)` in cases where you **do** care what thread execution is returned to?

Yes, any explicit `ConfigureAwait(...)` of any setting will not be changed by the directive. See https://github.com/Fody/ConfigureAwait#example for examples.

**Review by erikgabbard — APPROVED** [review]
I think that the usage of these "weavers" in this project to change the default behavior of `await` to **not** capture the execution context is a great way to eliminate the boilerplate `ConfigureAwait(false)` since that is probably the behavior what we want for almost (if not) all asynchronous calls.

If we do intend to integrate this into Create/Control then we will need to be very meticulous about adding in the calls to `ConfigureAwait(true)` on all calls awaited on the UI thread otherwise we will see random deadlocks where we miss them.

**Review by Gishe — APPROVED** [review]
I understand in this library code that this is what is desired.  I don't see migrating use of this into non library code.  When dealing with UI it is better to assume you want the context rather than the other way around.

**Pull request merged**
